### ISSUE TITLE
key part of the website can't be translated?

### ISSUE THREAD

**Issue by harcesz** [mastodon/joinmastodon#129]
It seems the main part of the website is not in the translation strings? 

![Zrzut ekranu z 2020-10-16 17-53-20](https://user-images.githubusercontent.com/1368026/96280806-ba6d2600-0fd8-11eb-9e02-7688366e82c2.png)

As you can see the top bar is translated (to Polish in this case), but the page 'body' is in English, and not in [strings in the repo](https://github.com/tootsuite/joinmastodon/tree/master/src/locales).

**Comment by Aikatsui** [comment]
#129 Outdated
