### ISSUE TITLE
Can I still collaborate here?

### ISSUE THREAD

**Issue by EuriNaiz** [mastodon/joinmastodon#151]
I was looking some translation that I want to improve and fix some orthography, but the repo is moved to Mastodon Gitlab, and the registration's closed, I didn't found how to create an account in the GitLab.

**Comment by Gargron** [comment]
All translations are on https://crowdin.com/project/joinmastodon

**Comment by EuriNaiz** [comment]
Thank You.

**Comment by EuriNaiz** [comment]
Ready, I have suggested some translations, but I cannot understand why the site is loading the Spanish (Argentina) by default in the site, I don't even have got installed that language in my system and/or browser; by default Spanish should be displayed, except if you have your system in Spanish (Argentina) (We have different spellings and conjugations...)
