### ISSUE TITLE
Regional / linguistic instance list confusion, maybe need a Languages category?

### ISSUE THREAD

**Issue by FediVideos** [mastodon/joinmastodon#160]
Someone asked me today for suggestions for Portuguese language instances (they said anything from Portugal or Brazil was ok). I checked on JoinMastodon's Regional list, and there is only one site listed: masto.pt

However, when I checked JoinMastodon's General list there were two Portuguese language sites listed: mastodon.com.br and social.coletivos.org (but not masto.pt!)

To add to the confusion, General seems to contain instances in some languages that are completely absent from Regional, but does not list all instances in these languages. People looking for these languages in Regional may incorrectly assume there are no instances in those languages, and even people looking in General will miss some instances in those languages.

This situation may be confusing for people who are just looking for an instance in their own language? Maybe there should be a "languages" category right at the top that contains all instances organised by language, regardless of their topic?

(I know there's a language filter within categories, but there is no option for displaying all instances in all categories in a particular language)

**Comment by nemobis** [comment]
> Someone asked me today for suggestions for Portuguese language instances

If you want comprehensive lists you can use for instance
* https://mastodon.help/instances/en?lang=407
* https://mastodon.fediverse.observer/list

**Comment by Gargron** [comment]
Added filtering by regions, stopped filtering by General category by default, so probably this is addressed now
