### ISSUE TITLE
New Tootle logo

### ISSUE THREAD

**Issue by Anomalion** [mastodon/joinmastodon#167]
Tootle has got a new logo, so it should probably be updated (for the https://joinmastodon.org/apps overview):
![tootle](https://user-images.githubusercontent.com/31505999/165151692-934e70c5-f251-4dcb-bbb2-69d1222e8668.svg)

**Comment by Anomalion** [comment]
The original source can be found here: https://github.com/bleakgrey/tootle/blob/master/data/icons/color.svg

**Comment by dixita0607** [comment]
Hi @Anomalion,
Is **Tootle** part of the list already? I thought of raising a PR to update the logo, But I couldn't find the app in the list itself. Is it called something else? Let me know. Would be happy to help :)

**Comment by andypiper** [comment]
It looks like this app has been retired so I'm going to close this as not needed.
