### ISSUE TITLE
mention that mastodon is not the only software in the fediverse

### ISSUE THREAD

**Issue by Johann150** [mastodon/joinmastodon#175]
The official web presences of Pleroma (<https://pleroma.social/>), Misskey (<https://misskey-hub.net/>), Peertube (<https://joinpeertube.org/>) and probably more acknowledge Mastodon as another ActivityPub implementation on the first web page by mentioning it by name.
Edit: The Misskey web presence has since been amended to mention Mastodon in text in addition to showing its logo.

Mastodon does not acknowledge that there are any other ActivityPub servers, at least I could not find anything like that. It would be nice if you return the favor.
- - -
Ideally it would be nice to also reword the front page to not imply that Mastdon is a network in itself.
> Mastodon isn’t a single website [...], it's a network of thousands of servers [...].

The network that unites us is the Fediverse and not Mastodon.

**Comment by Gargron** [comment]
I think this is now addressed
