### ISSUE TITLE
Sponsor spot is too cheap for commercial organisations

### ISSUE THREAD

**Issue by SaphireLattice** [mastodon/joinmastodon#177]
I think that 10/20$ is rather.. extremely generous for something like a casino to pop up on a site that gets a lot of traffic from new users. It's a basically rounding error for budget of these organizations, yet it happily promotes them

Commercial organizations should really require something like 500-1000 USD to appear so far up, especially if it's something like, again, a casino or a cryptocurrency thing. And scale based on type of the org and donation they give, preferably unable to overtake non-commercial and government organizations

Again, 20 USD/mo is nothing for some types of highly abusive and harmful organizations that can easily donate to patreon, and I would prefer if they either contributed some actual significant amount, or never appeared on the list.

Edit: Ah, did not expand the list of sponsors and it is 100$/mo... which is still sadly rather generous for these types of places. I am pretty sure google ads with similar impact will cost *much* more, etc...

**Comment by Gargron** [comment]
I haven't updated the prices in a long time, so this is a good call.

**Comment by Gargron** [comment]
Prices updated...
