### ISSUE TITLE
Add F-Droid link to downloads

### ISSUE THREAD

**Issue by samuraikid0** [mastodon/joinmastodon#183]
![68747470733a2f2f6664726f69642e6769746c61622e696f2f617274776f726b2f62616467652f6765742d69742d6f6e2e706e67](https://user-images.githubusercontent.com/46766062/168503672-0ce0c740-aa5a-48fa-ad99-7ab34d296ed9.png)

Cheers !

**Comment by samuraikid0** [comment]
For future reference,  since a issue was already open on android

https://github.com/mastodon/mastodon-android/issues/5

**Comment by riveravaldez** [comment]
> But official app isn't available on F-Droid (yet?)

Hi, I don't know why this proposal was closed, but right now a _Mastodon_ search[0] on F-Droid's website produces a good number of clients (_Tusky_ included[1]) which I guess would be reasonable candidates for appearing in Mastodon's _Apps_ webpage[2] on the _Browse third-party apps_ section...

Does anybody know why this is not the case?

[0] https://search.f-droid.org/?q=mastodon&lang=en
[1] https://f-droid.org/en/packages/com.keylesspalace.tusky/
[2] https://joinmastodon.org/apps
