### ISSUE TITLE
"get on waitlist" is misleading

### ISSUE THREAD

**Issue by FediVideos** [mastodon/joinmastodon#194]
The new server list page has replaced "request an invite" with "get on waitlist". The old phrase was much better than the new one, and may people off trying to join.

"Get on waitlist" implies that the server is full and may not have space for you, that there will be a long delay in joining. In reality, a lot of instances process applications very quickly and only use the request system so they can manually filter out obvious spammers.

**Comment by Gargron** [comment]
> that there will be a long delay in joining

This is the reality

**Comment by brookmiles** [comment]
> > that there will be a long delay in joining
> 
> This is the reality

Can you expand on what you are seeing that we are not? How long do you see as a typical delay?

I agree with OP that "get on waitlist" is misleading for my instance. There is no waitlist.  The only thing an applicant has to wait for is for me to wake up and read my email, which is likely going to be 8-12 hours tops.

Waitlist to me implies a "full" server, and that an applicant might need to wait days/weeks, for "space" to open up, which is not the case.

I agree that the current wording is likely to unnecessarily discourage prospective users.

**Comment by FediVideos** [comment]
From personal experience, when I've signed up on servers which ask you to say why you want to join, they've processed my application within a day or two. I've never waited longer than that.

If there's a genuine waitlist, surely they would say so on the sign-up form? Or they would close sign-ups?

**Comment by FediVideos** [comment]
Perhaps the server list could say "Apply to join"?

"Apply to join" would cover all scenarios, including fast processing or waitlists. "Join Waitlist" implies only one scenario.

**Comment by tathamoddie** [comment]
Resolved by 18ef2f42abc70c5158110ef1330849f631b8860b

**Comment by FediVideos** [comment]
Yay, thank you so so much to the site devs, the new phrase is brilliant, much more accurate! :clap:
