### ISSUE TITLE
pictures (alt and translation of screenshots)

### ISSUE THREAD

**Issue by Saimyx** [mastodon/joinmastodon#199]
Hello,
First, are you planning to set up alt attributes pictures ? It's important for accessibility.

And for screenshots, will you make a possibility to suggest a translated picture ?

To finnish, I think there is a typo in "Mastodon gGmbH" there will be "Mastodon GmbH".

In any case, it's a very good job this website !

**Comment by Gargron** [comment]
"Mastodon gGmbH" is correct.

The screenshots are presentational.
