### ISSUE TITLE
Logo usage hierarchy issue?

### ISSUE THREAD

**Issue by nclm** [mastodon/joinmastodon#211]
On the [brand page](https://joinmastodon.org/branding), the “usage hierarchy” states:
1. Purple mark and white wordmark on black background.
2. White mark and black wordmark on white background.
3. Black mark and white wordmark on black background.

But a white mark on a white background or a black mark on a black background means that the mark would be invisible? There might be something to fix here.

Additionally you might also want to describe the backgrounds as “dark” and “light” instead of “black” and “white” (or “black or dark” and “white or light” at least), as the exact background colour where the logo is inserted depends on the own brand of wherever the logo is inserted.

**Comment by Gargron** [comment]
Yeah, I'm aware the black and white logos aren't usable currently. Waiting on assets.

**Comment by nclm** [comment]
This seems solved :)
