### ISSUE TITLE
Undermoderated instances

### ISSUE THREAD

**Issue by tusooa** [mastodon/joinmastodon#237]
From https://joinmastodon.org/covenant :
> Active moderation against racism, sexism, homophobia and transphobia
>
> Users must have the confidence that they are joining a safe space, free from white supremacy, anti-semitism and transphobia of other platforms

I found out that these instances are undermoderated, and thus does not conform to the criterion above.

- o3o.ca
  - https://o3o.ca/@Icebear/108900568939770924 - transphobia - no action taken
  - https://o3o.ca/@blue_stone/108636488173422852 - fatphobia - no action taken
- m.cmx.im
  - https://m.cmx.im/@harumonica/108405674380844668 - intentionally misgendering - no action taken
  - https://m.cmx.im/@AChiW/108736426573187022 - transphobia (gender-essentialism) - no action taken

**Comment by cmx-im** [comment]
Hello, Tusooa.

Thank you for bringing this to our attention.

On a daily basis, we have a dedicated team that actively moderates against racism, sexism, homophobia, transphobia, and other inappropriate content.

The content that we deemed to be in violation of the rules was removed, and the accounts were penalized.

**We encourage users to use the report functionality to notify us of such activity**, as this is the most efficient way to notify us rather than raising a Github issue.

Team CMX.im

**Comment by tusooa** [comment]
> Hello, Tusooa.
> 
> Thank you for bringing this to our attention.
> 
> On a daily basis, we have a dedicated team that actively moderates against racism, sexism, homophobia, transphobia, and other inappropriate content.
> 
> The content that we deemed to be in violation of the rules was removed, and the accounts were penalized.
> 
> **We encourage users to use the report functionality to notify us of such activity**, as this is the most efficient way to notify us rather than raising a Github issue.
> 
> Team CMX.im

All links in this issue are reported by me *months ago*.

**Comment by cmx-im** [comment]
> All links in this issue are reported by me _months ago_.

Hello, Tusooa.

We moderate transphobia contents that include **fear, harassment, bullying, aversion, hatred, violence or anger towards transgender people or transness in general**. We reviewed multiple reports you sent us. Some of them, according to the aforementioned understanding of "transphobia contents", do not constitute transphobia. We had taken immediate action within 48 hours after your reports were sent for some other posts that were indeed transphobic.

Furthermore, please keep in mind that if users do not include the specific post or URL that is believed to be in violation in their reports, and such content cannot be found on the first few pages of the reported user's profile, it will be impracticable for us to read through hundreds of posts from the reported users to determine which post was in violation.

**Comment by o3o-ca** [comment]
O3O.CA Instance Announcement: 
https://o3o.ca/@o3o_bulletin/109377334018853729
