### ISSUE TITLE
HTML character codes, like `&mdash`, on translated pages

### ISSUE THREAD

**Issue by ranfdev** [mastodon/joinmastodon#246]
On https://joinmastodon.org/it/servers
`&mdash` gets inserted as normal text.

![Screenshot from 2022-11-10 23-01-39](https://user-images.githubusercontent.com/23294184/201215210-fdddd14d-8fcb-4236-b347-25d02e35434f.png)

The same issues appears on every translated language.
Tested on the latest firefox on desktop and tested on brave for mobile.

**Comment by jsoref** [comment]
It isn't limited to `&mdash;`.

https://joinmastodon.org/de/servers

<img width="501" alt="image" src="https://user-images.githubusercontent.com/2119212/205514830-108bcb8d-d042-4c0f-98f1-5064cc5f1b92.png">

https://github.com/mastodon/joinmastodon/blob/70f73ecaf7ad242de8230d675529aa247a614a00/locales/de.json#L105

https://joinmastodon.org/es/servers
<img width="516" alt="image" src="https://user-images.githubusercontent.com/2119212/205514916-b1dcacd3-ef4e-47fb-850c-8347f8253f1e.png">

https://github.com/mastodon/joinmastodon/blob/70f73ecaf7ad242de8230d675529aa247a614a00/locales/es.json#L105

<img width="521" alt="image" src="https://user-images.githubusercontent.com/2119212/205514953-a5e70354-cfeb-4363-a120-306707bdff9e.png">

https://github.com/mastodon/joinmastodon/blob/70f73ecaf7ad242de8230d675529aa247a614a00/locales/eu.json#L105

**Comment by jsoref** [comment]
Alternatively, the JSON decoder could construct an HTML textarea, insert the returned JSON into it and extract the decoded HTML: https://stackoverflow.com/posts/7394787/revisions

**Comment by roydigerhund** [comment]
I fixed it in this pull request https://github.com/mastodon/joinmastodon/pull/275 by using the unicode version `\u2013`.
