### ISSUE TITLE
HTML-encoded characters are shown in non-english languages

### ISSUE THREAD

**Issue by renchap** [mastodon/joinmastodon#269]
For example, on https://joinmastodon.org/fr/servers I see:

> Mastodon n’est pas un site Web unique. Pour l’utiliser, vous devez créer un compte chez un fournisseur&mdash;nous les appelons serveurs&mdash;qui vous permettra d’entrer en contact avec d’autres personnes à travers Mastodon.

And in german https://joinmastodon.org/de/servers:

> Mastodon ist keine einzelne Webseite. Um es nutzen zu können, musst du ein Konto bei einem Anbieter erstellen &ndash; wir nennen sie Server &ndash; der dich mit anderen Personen über alle Mastodon-Instanzen hinweg vernetzen lässt.

I think the translated files should use the non-HTML-encoded character, and it will then be correctly encoded by the i18n library in the resulting page.

**Comment by roydigerhund** [comment]
Github decoded the dashes correct in your examples, here are screenshots of the wrong decoded text snippet on the website.

<img width="541" alt="image" src="https://user-images.githubusercontent.com/10884413/208971549-661091fd-2cac-4553-b377-864009f30c86.png">
<img width="498" alt="image" src="https://user-images.githubusercontent.com/10884413/208971568-7fe5cef1-9923-424f-a05f-0f772bab41b1.png">

**Comment by renchap** [comment]
Fixed in https://github.com/mastodon/joinmastodon/commit/b387b7bef41961ae2cdd9baaf768d25c0114a25b
