### ISSUE TITLE
Issue with formatting in French

### ISSUE THREAD

**Issue by privacytime101** [mastodon/joinmastodon#280]
Viewing /fr/servers results in the following description: 

"Mastodon n’est pas un site Web unique. Pour l’utiliser, vous devez créer un compte chez un fournisseur&mdash;nous les appelons serveurs&mdash;qui vous permettra d’entrer en contact avec d’autres personnes à travers Mastodon."

The "&mdash" is the issue.

Webkit-based browser; iOS 16.3 Beta

Edit: Sorry, I realize now that the "&mdash" formatted correctly in this issue, but they are spelled out on the site

**Comment by renchap** [comment]
Duplicate of #246
