### ISSUE TITLE
Add Megalodon to Android apps

### ISSUE THREAD

**Issue by cassidyjames** [mastodon/joinmastodon#293]
I have been using and loving Megalodon, a Mastodon app for Android that is based on the official app codebase but with its own branding, features, and personality. It would be nice to add it to the list of clients for Android, as it is always the one I recommend.

https://play.google.com/store/apps/details?id=org.joinmastodon.android.sk

**Comment by MKCOOL142** [comment]
I would also say to add moshidon while you're at it

**Comment by nemobis** [comment]
As it wasn't mentioned above: Megalodon is under GPLv3 https://sk22.github.io/megalodon/
