### ISSUE TITLE
i18n: add Occitan locale

### ISSUE THREAD

**Issue by Mejans** [mastodon/joinmastodon#309]
Hello,
I finished the translation into Occitan on the Crowdin platform.
Would it be possible to add it to the web site?
Regards

**Comment by xmgz** [comment]
locales have been updated here (2 months ago) but are not available in drop down menu for selection on joinmastodon.org 

some other translated languages (at 100%) are missing :(


thanks for open this issue.

**Comment by Mejans** [comment]
Hello @Gargron would it be possible to have a look at this PR please?

**Comment by andypiper** [comment]
Duplicate of #213
