### ISSUE TITLE
New default filter prevents discovery of manual review servers

### ISSUE THREAD

**Issue by joshuap** [mastodon/joinmastodon#318]
I noticed that @Gargron recently changed the filters on the server picker (58089ccad65d4b5e684983bb916109596e7f2967) to default to instant sign-up servers. I can imagine some reasons for such a change, but I think in practice it will prevent users from discovering manual-review servers, since the "Sign-up process" dropdown is not very obvious in the UI.

Anecdotally, I'm the admin of federated.press (manual review, journalism category), and since the change, I haven't had any new signups at our server. I normally review 10+ per day. I am hesitant to open registration because we are underfunded and our moderation team (me 😁) isn't ready to handle a general influx of users.

Anyway, feel free to close this issue if it's not something you wish to revisit—but I wanted to mention it!

**Comment by Gargron** [comment]
[eb4a35f](https://github.com/mastodon/joinmastodon/commit/eb4a35fd80c3d9bf640450429c2be1ec40c1ead5)
