### ISSUE TITLE
Apps to add

### ISSUE THREAD

**Issue by nclm** [mastodon/joinmastodon#327]
There are some good quality apps that could be added to [the very useful Apps page](https://joinmastodon.org/apps).

To avoid flooding the “Issues” with these, I’m opening this with the idea that it could be used as a meta issue so that apps can be suggested there, possibly one per post. Let me know if that’s not a good process.

Additionally, there’s the general question about what’s the criteria for adding an app or not on the page? Is it aiming to be exhaustive or selective? Does it only contains apps that have been maintained within the last X months, or with at least X maintainers, etc?

**Comment by nclm** [comment]
**Elk** (Web, Free)
* URL: https://elk.zone
* Logo: https://raw.githubusercontent.com/elk-zone/elk/main/public/logo.svg
* Release: 2023-01-10

**Comment by nclm** [comment]
**Phanpy** (Web, Free)
* URL: https://phanpy.social/
* Logo: https://raw.githubusercontent.com/cheeaun/phanpy/main/design/logo-4.png
* Release: 2022-12-15

**Comment by nclm** [comment]
Pinafore, currently listed, is unfortunately [not maintained any more](https://nolanlawson.com/2023/01/09/retiring-pinafore/). Maybe it can be replaced with its fork, Semaphore?

**Semaphore** (Web, Free)
* URL: https://semaphore.social
* Logo: https://raw.githubusercontent.com/NickColley/semaphore/main/src/static/semaphore-logo.svg
* Release: 2023-01-22 (or keep same as Pinafore)

**Comment by nclm** [comment]
**Tuba** (Desktop Linux, Free)

- URL: https://tuba.geopjr.dev/
- Logo: https://tuba.geopjr.dev/assets/icons/logo.svg
- Release: 2023-03-23

**Comment by dixita0607** [comment]
> **Elk** (Web, Free)
> 
> * URL: https://elk.zone
> * Logo: https://raw.githubusercontent.com/elk-zone/elk/main/public/logo.svg
> * Release: 2023-01-10



> Pinafore, currently listed, is unfortunately [not maintained any more](https://nolanlawson.com/2023/01/09/retiring-pinafore/). Maybe it can be replaced with its fork, Semaphore?
> 
> **Semaphore** (Web, Free)
> 
> * URL: https://semaphore.social
> * Logo: https://raw.githubusercontent.com/NickColley/semaphore/main/src/static/semaphore-logo.svg
> * Release: 2023-01-22 (or keep same as Pinafore)

These two seems to be already part of the list. 



> Pinafore, currently listed, is unfortunately [not maintained any more](https://nolanlawson.com/2023/01/09/retiring-pinafore/). Maybe it can be replaced with its fork, Semaphore?
> 
> **Semaphore** (Web, Free)
> 
> * URL: https://semaphore.social
> * Logo: https://raw.githubusercontent.com/NickColley/semaphore/main/src/static/semaphore-logo.svg
> * Release: 2023-01-22 (or keep same as Pinafore)

Someone has created a PR for this one https://github.com/mastodon/joinmastodon/pull/339. It should be soon merged by the maintainers.

**Comment by textoo** [comment]
There is already a place for that, to submit an app you have to make a Pull Request ( https://github.com/mastodon/joinmastodon/pulls ) , this is usualy done by the app developers, but nothing prevents third party from doing it.

**Comment by andypiper** [comment]
I'm going to close this issue as most of these are now on the site and I've now added a [Contributing](https://github.com/mastodon/joinmastodon/blob/master/CONTRIBUTING.md) guide to outline what is needed to have an app added. Working through the PR backlog on these. 🙏🏻

**Comment by andypiper** [comment]
FWIW I took inspiration from the questions from @nclm and added some more context to the process for adding apps to the list in [the CONTRIBUTING.md file](https://github.com/mastodon/joinmastodon/blob/master/CONTRIBUTING.md). Thank you 🙏🏻️
