### ISSUE TITLE
Account login page for account deletion 

### ISSUE THREAD

**Issue by Mattis142** [mastodon/joinmastodon#338]
under the new play store rules apps will next year have to offer an account deletion form, I assume that's going to have to be a centralized URL so why not make a Page where the user simply has to type in their instance name, then gets redirected to their instances sign in page (preferably with some kind of "?redirect=settings-accountdeletion" Parameter at the end of the URL or whatever, I don't know if mastodon allows for something like that yet so it might be a good idea to add if it currently doesn't) and can from there delete their account. 

https://android-developers.googleblog.com/2023/04/giving-people-more-control-over-their-data.html?m=1

**Comment by andypiper** [comment]
I think this issue probably belongs in the main `mastodon/mastodon` repository rather than in the Mastodon website repository, so I'm going to close this. Thanks.
