### ISSUE TITLE
Roadmap not readable on mobile

### ISSUE THREAD

**Issue by ThisIsMissEm** [mastodon/joinmastodon#346]
Related #294 

I'm opening this mostly so I don't forget to do a PR, but I noticed that the roadmap's text doesn't wrap on mobile, which means the items that are longer than a devices screen width can't be properly read.

![IMG_5057](https://user-images.githubusercontent.com/30827/234584673-066fe4c4-8ed8-4bb5-85d2-ecc5dadb9337.png)

**Comment by ocdtrekkie** [comment]
Another big part of this problem is that the roadmap doesn't show the categories on mobile. This means it often doesn't make any sense. Features are listed Mastodon already has because... they refer to mobile app support items which aren't indicated in this view.

**Comment by ThisIsMissEm** [comment]
> Another big part of this problem is that the roadmap doesn't show the categories on mobile. This means it often doesn't make any sense. Features are listed Mastodon already has because... they refer to mobile app support items which aren't indicated in this view.

@ocdtrekkie ah, yeah, that's the issue linked at the very top of this issue.

**Comment by ThisIsMissEm** [comment]
Have opened https://github.com/mastodon/joinmastodon/pull/347 — provided vercel builds and deploys it, I'd definitely appreciate people taking it for a spin and seeing if it "looks right"

**Comment by ThisIsMissEm** [comment]
Given #347 has been merged, I'm closing this.
