### ISSUE TITLE
Trying to signup our instance library.love but instances.social cant find it

### ISSUE THREAD

**Issue by paulamackinnon** [mastodon/joinmastodon#348]
Our instance library.love has been up for a month, people are signing up directly but we would like to be listed on joinmastodon.org. our categories would be libraries, books North America United States. Any guidance is appreciated! -Paula

**Comment by dixita0607** [comment]
This issue can be closed as the library.love instance is listed on [joinmastodon.org](https://joinmastodon.org/servers) under "Books" category.
