### ISSUE TITLE
I made a new Mastodon app for Android

### ISSUE THREAD

**Issue by tangxiangpi** [mastodon/joinmastodon#354]
### Pitch

I developed app Focus For Mastodon (Android), the core experience from Focustwitter (currently the best third -party Twitter client). Can you add it to the homepage of the Mastodon App?
https://play.google.com/store/apps/details?id=allen.town.focus.mastodon

### Motivation

ALL

**Comment by textoo** [comment]
You have to create a Pull Request https://github.com/mastodon/joinmastodon/pulls to submit your app.
Just be aware this may take a while, mine was submited 4 months ago and it still hasn't been merged.

**Comment by andypiper** [comment]
Focus added. Thank you!
