### ISSUE TITLE
Annual report for 2022

### ISSUE THREAD

**Issue by progval** [mastodon/joinmastodon#371]
Hi,

In February 2022, Mastodon published the [annual report for 2021](https://joinmastodon.org/reports/Mastodon%20Annual%20Report%202021.pdf). Do you have an ETA for the 2022 annual report?

Thanks

**Comment by nemobis** [comment]
From https://www.unternehmensregister.de/ureg/showDepositTree.html?submitaction=deposits&company=4889975 I see that the documents for 2021 were only submitted to the register on 2023-04-28. Hopefully Mastodon gGmbH can catch up and be a bit faster with the 2022 reporting, now that it has more staff. 

If not, I recommend spending more on professional help with (FLOSS) (non-profit) governance; it may sound like "administrative costs" or overhead, but it's necessary for the entity to avoid far costlier mistakes.

**Comment by andypiper** [comment]
This is absolutely being worked on *right now* - as you are aware it has been an unexpectedly busy period since Nov 2022. No ETA, but "very soon". Thank you!

**Comment by progval** [comment]
https://joinmastodon.org/reports/Mastodon%20Annual%20Report%202022.pdf

**Comment by nemobis** [comment]
For completeness, I'm also attaching the officially deposited financial statements, which declare assets of 246&nbsp;594,47 €.

[Hinterlegung_2024-04-27.pdf](https://github.com/mastodon/joinmastodon/files/15139183/Hinterlegung_2024-04-27.pdf)
