### ISSUE TITLE
Investigate: is Tooter (SailfishOS) still maintained?

### ISSUE THREAD

**Issue by andypiper** [mastodon/joinmastodon#384]
The website linked from here has code last updated in 2017. I'm not a SailfishOS user so I am not able to verify whether this app is still active or useful.

**Comment by jazmichaelking** [comment]
I believe this is the current fork: https://github.com/poetaster/harbour-tooter 

Context: https://forum.sailfishos.org/t/tooter-feedback-thread/13508

**Comment by andypiper** [comment]
Removed the SailfishOS section in https://github.com/mastodon/joinmastodon/commit/2823b7bdc1f05405987375692d4e653551fcd16d
