### ISSUE TITLE
no images showing 

### ISSUE THREAD

**Issue by minniehaha** [mastodon/joinmastodon#393]
Is it server mastodon.social, but there are no images anywhere? Or is it Mastodon source code that has a bug? Profile, in post, nothing. Attempt to upload just gives an empty placeholder. And briefly, a thumbnail of the uploaded image. 
On the face of it, images appear to be uploading, and the software reports success in error.
Used on Edge and Chrome in Windows 11, and IOS 16.5.1 (c)
Can provide screenshots on request.

**Comment by andypiper** [comment]
This repository is for the joinmastodon.org website rather than for the mastodon.social instance, so I'm closing this as invalid. If you happen to be able to access the Discord (a perk of donating via Patreon) then you might want to report this issue there.
