### ISSUE TITLE
DEFAULT_LANGUAGE or DEFAULT_LOCALE ?

### ISSUE THREAD

**Issue by manuviens** [mastodon/joinmastodon#446]
https://github.com/mastodon/joinmastodon/blob/444bc309e7b770a2078759728ae380365338c4e4/pages/covenant.tsx#L77

It's mentioned DEFAULT_LANGUAGE, but in the doc it's [DEFAULT_LOCALE](https://docs.joinmastodon.org/admin/config/#default_locale).

**Comment by ClearlyClaire** [comment]
It should be `DEFAULT_LOCALE` indeed.
