### ISSUE TITLE
The "Join mastodon.social" and "Pick another server" buttons are not translated

### ISSUE THREAD

**Issue by fabianegli** [mastodon/joinmastodon#451]
This seems to be systematic. Is it intended that these buttons remain english in all language versions? 

<img width="1269" alt="Screenshot 2023-11-09 at 18 02 24" src="https://github.com/mastodon/joinmastodon/assets/8569110/1e4980f7-673d-46a6-bc73-63906babe1f4">

It would be great to have the buttons translated, too.

**Comment by renchap** [comment]
Those buttons should be translated, but translations have not been imported from Crowdin in a long time.

I will try to fix this.

**Comment by renchap** [comment]
The translation sync process is now automated, it should allow us to merge translations much quicker.

Those buttons should soon be translated :)
