### ISSUE TITLE
Update sponsors page to include relevant links and information

### ISSUE THREAD

**Issue by mlcohen** [mastodon/joinmastodon#470]
Suggested sponsors [page](https://joinmastodon.org/sponsors) updates:

- Include a link to Mastodon's Github sponsors [page](https://github.com/sponsors/mastodon/)
- include a link to Mastodon's one-time donation [page](https://donate.stripe.com/00g5l42h8ezY3YcaEE)
- Include an additional section on the Mastodon sponsors page that briefly explains what donations fund
- Include a link to the most recent annual report

**Comment by RaviiiiYadav** [comment]
Hey andypiper I think I can work on it.

**Comment by RaviiiiYadav** [comment]
Can you please assign it to me.

**Comment by andypiper** [comment]
Thank you for the offer to help. I’ve assigned to you, but please be aware that your pull request will need to be reviewed by a member of the team before anything is merged for deployment.

**Comment by andypiper** [comment]
@RaviiiiYadav I am so sorry for the confusion - I’ve assigned to @mlcohen who was already working on the issue, it should have been assigned to them already. My mistake completely. We do still appreciate offers of support for the website across any of the open issues here.
