### ISSUE TITLE
Untranslated string on homepage

### ISSUE THREAD

**Issue by sveinki** [mastodon/joinmastodon#479]
On the opening page of https://joinmastodon.org/ there is an untranslatable string below the Sponsors-section:
"Sponsorship does not equal influence. Mastodon is fully independent."
IMHO it should be translatable.

**Comment by andypiper** [comment]
Well spotted - let me look into this.

**Comment by renchap** [comment]
Mmh, we are missing a Github action to ensure that strings have been extracted when added

**Comment by renchap** [comment]
This is now properly fixed, the source strings have been synced with Crowdin and can be translated there.

**Comment by sveinki** [comment]
Cool, the string has landed in Crowdin. Thanks for very swift action!
