### ISSUE TITLE
Add web app "Semaphore"

### ISSUE THREAD

**Issue by Krinkle** [mastodon/joinmastodon#504]
https://joinmastodon.org/apps

https://semaphore.social/ has been operating for a good year now as the continuation of Pinafore, which was discontinued in 2022.

* https://github.com/nolanlawson/pinafore
* https://github.com/NickColley/semaphore

I suggest adding Semaphore, and potentially for new users delisting Pinafore as new recommendation.

/cc @nolanlawson @NickColley

**Comment by NickColley** [comment]
I think given I haven't had the time to dedicate to Semaphore as I'd liked that just leave this as is for now.
