### ISSUE TITLE
Add Ice Cubes as a desktop app

### ISSUE THREAD

**Issue by codenyte** [mastodon/joinmastodon#582]
Ice Cubes is currently only marked as an iOS app, but it is also available on macOS, as can be seen on [their GitHub](https://github.com/Dimillian/IceCubesApp/) and [App Store page](https://apps.apple.com/us/app/ice-cubes-for-mastodon/id6444915884?platform=mac).

**Comment by andypiper** [comment]
That could be my mistake based on the way I added it, thanks for the nudge, I shall recheck.
