### ISSUE TITLE
Interlingua language request

### ISSUE THREAD

**Issue by softinterlingua** [mastodon/joinmastodon#725]
I want to request to add Interlingua (ia) language for translation at Crowdin.
Previously i requested it in the project forum https://crowdin.com/project/joinmastodon/discussions/344

Currently we have fully translated the web app and Mastodon for Android app.

**Comment by andypiper** [comment]
@renchap @Gargron can this be enabled on Crowdin across the Mastodon projects?

**Comment by renchap** [comment]
This has been enabled!
