### ISSUE TITLE
Megalodon removed from Google Play Store

### ISSUE THREAD

**Issue by p37307** [mastodon/joinmastodon#760]
Megalodon has been removed from Google Play Store. 

You might want to adjust the apps options at Join Mastodon and remove the Google Play Store link..

**Comment by ClearlyClaire** [comment]
Is there any information on this, and whether this might be temporary?

**Comment by andypiper** [comment]
It looks like perhaps it is no longer being developed? https://floss.social/@megalodon/112836883325354378

I'll see whether the project can be contacted directly before we remove it as I'd like to understand whether this is something that is intended.

**Comment by andypiper** [comment]
OK, going to remove this.
