### ISSUE TITLE
Add Hindi Language translation

### ISSUE THREAD

**Issue by dipanshurdev** [mastodon/joinmastodon#764]
Hi, I noticed that my native language, Hindi is not added.

I would like to request the addition of Hindi as a language translation. It would make the application accessible to an even wider audience.

If you need help with adding translation, I would be happy to contribute.

### screenshot

![Screenshot 2024-08-29 115758](https://github.com/user-attachments/assets/94052999-0d62-41c2-8b2d-c7bc863f8a92)

**Comment by andypiper** [comment]
Thank you for the offer. Please [follow the guidance in the README](https://github.com/mastodon/joinmastodon/blob/main/README.md#translations) for adding translations.

**Comment by dipanshurdev** [comment]
Hi @andypiper , I have completed the Hindi translations on Crowdin as per the project's guidelines.
Please check and ensure that the translations are synced to the repository.

Please let me know if there's anything else I need to do on my end.

**Comment by andypiper** [comment]
Thank you for your patience, I had not realised that this had not been enabled in the user interface. This has been resolved in https://github.com/mastodon/joinmastodon/commit/451c3316f4e376eeb04f7132273cf22147f84977

**Comment by dipanshurdev** [comment]
> Thank you for your patience, I had not realised that this had not been enabled in the user interface. This has been resolved in https://github.com/mastodon/joinmastodon/commit/451c3316f4e376eeb04f7132273cf22147f84977

Nice 💯
