### ISSUE TITLE
How to get a server listed? Been trying for 1,5+ years at this point

### ISSUE THREAD

**Issue by smiba** [mastodon/joinmastodon#778]
Hi,

Sorry for being a little disruptive by making a GitHub issue, but we've been trying to get our instance listed for over one and a half years now. (approaching 2 years in a few months)

We've sent numerous mails to hello@joinmastodon.org, back when this email was still listed and never got a response. We'd love to get listed under the "Furry" category.

Here is a copy of our original email sent on the 28th of January 2023:
```
Hi,

I'm submitting my instance to be listed on the [joinmastodon.org](http://joinmastodon.org/) website.
I've been running an instance for a couple of months now and everything has been running smoothly and has been configured so we can easily scale to support thousands of users.

For more information about the hardware and current setup please check the about page!: https://woof.tech/about

Instance information:

Domain name: [woof.tech](http://woof.tech/)
Backups: Twice a day (of both PSQL & Redis) to external private S3 bucket
Location: Europe (Mixed). Server: Finland, S3 Storage: The Netherlands, CDN storage: Germany (with static replication to the US for latency reasons)
Category: LGBTQ+ & Furry (and possibly tech as the domain suggests)

In case I go AWOL, a good and trusted friend of mine has an SSH key and has a secondary account with the appropriate IAM access to manage the server.

If the instance ever shuts down (unlikely considering I use it myself as well), I will give users 3 months minimum to move, but likely much longer. I understand the responsibility hosting an instance entails.
Additionally I'm a Linux Sysadmin by trade with experience in scaling and optimizing web delivery. I've also done some feature requests and pull requests on the mastodon repo. I believe I have a solid understanding of mastodon's backend and functionality.

If there are any questions or information that might be required, don't hesitate to let me know.

Kind regards,
<Full name>
~Purple@woof.tech
```

Considering there has only been one single Furry instance that is open for registration (non-approval) for a good year now, we'd still very much love to be added. I've designed our infrastructure around handling much more users than the ~100 we have had for years now.

Anyways if anyone from Mastodon could let us know the status of listings on join mastodon (are they being processed at all), or what the right email is nowadays, please let me know!

**Comment by smiba** [comment]
@andypiper Hi, sorry to bother! Would you be able to take a look at this, as I've seen you've replied to similar requests in the past :)

Thanks!

**Comment by andypiper** [comment]
I've been at fediforum and I'll be on vacation next week but I will see what I can figure out here. Thanks for your patience.

**Comment by smiba** [comment]
Take your time! Enjoy your holiday, please don't interrupt it for me!

**Comment by smiba** [comment]
@andypiper Hope you had a nice holiday! 

Now that you're back again, just poking you about this :) 
I'd really appreciate if you could get the ball rolling, or forward me to someone who's responsible for listenings on joinmastodon 💜

**Comment by andypiper** [comment]
Thanks for the reminder. I'm sending this issue to someone who should be working on updating listings right now 🤞🏻

**Comment by andypiper** [comment]
Sorry for the confusion here - at some point we were switching systems for managing submissions and it looks like yours may have been lost. There should be enough here to get the instance added.

**Comment by smiba** [comment]
Thanks, much appreciated 💜

**Comment by smiba** [comment]
I see it's listed now, thank you so much!
